### PR TITLE
Add Firebase App Check example to starters

### PR DESCRIPTION
**Pull request by chocolatkey**

### CODE REVIEW

**Comment by kristianfreeman** [comment]
Thanks for the submission! We're not currently accepting contributions to the Quick Start section of the docs, though it's something we'd like to do in the future. Thanks for trying Workers!

**Comment by simplenotezy** [comment]
@chocolatkey did you ever figure out a solution for this?

**Comment by simplenotezy** [comment]
FYI just found this https://firebase.blog/posts/2021/10/protecting-backends-with-app-check/

**Comment by chocolatkey** [comment]
@simplenotezy Not quite sure what you mean by "solution", this PR includes my implementation in a link to a repo on my Github: https://github.com/chocolatkey/worker-appcheck-template . The point of this PR was to make it easily discoverable in the Cloudflare docs

**Pull request closed without merging**
