### PR TITLE
[Website] Fix link colour contrast 

### PR DESCRIPTION
**Pull request by Ekwuno**
There are some issues with the contrast of links when viewing docs in dark mode. These issues are fixed by this PR. 
it addresses #3928 and is a continuation of #3705.

### CODE REVIEW

**Review by kodster28 — APPROVED** [review]
LGTM, and checked the various examples @pedrosousa raised in the previous PR.

However, still would appreciate Pedro's detailed eye looking at this before we merge.
Preview is at https://ff4ba5b7.cloudflare-docs-7ou.pages.dev/

**Comment by pedrosousa** [comment]
I still found one occurrence of a blue link:
https://ff4ba5b7.cloudflare-docs-7ou.pages.dev/ruleset-engine/rules-language/functions/#function-uuidv4
image

Can you check, please?

**Comment by pedrosousa** [comment]
Also, this specific link also has a different color when using the light theme:
https://ff4ba5b7.cloudflare-docs-7ou.pages.dev/firewall/#availability
image

The dark theme version of this link looks fine.

The same light theme issue is also present in this table:
https://ff4ba5b7.cloudflare-docs-7ou.pages.dev/firewall/api/cf-firewall-rules/json-object/

**Comment by Ekwuno** [comment]
@pedrosousa the way we handle CSS for tables is a bit weird right now. However, can you provide a list of these links that need fixing so we can do them all in one PR? 

I will fix these ones now, and then merge them.

**Comment by pedrosousa** [comment]
Sure! These were the only ones I found last week.

**Pull request merged**
