### PR TITLE
[SSL] Update installation steps for keyless

### PR DESCRIPTION
**Pull request by cicku**
Do it in the yum/RPM style

### CODE REVIEW

**Review by kodster28 — APPROVED** [review]

**Comment by cicku** [comment]
Do we need `sudo` or not?

**Comment by kodster28** [comment]
Don't fully know. The best person to ask internally is Mitali.

**Comment by mitalirawat** [comment]
> Do we need `sudo` or not?

Tested your changes out, lgtm!
These would need a sudo with a non-root user. We can update it to have sudo here for both yum and dnf.

**Review by mitalirawat — APPROVED** [review]

**Comment by kodster28** [comment]
Good to merge in, @cicku?

**Comment by cicku** [comment]
Squash and merge please.

**Pull request merged**
