### PR TITLE
[Docs Site] Improved footnote experience

### PR DESCRIPTION
**Pull request by kodster28**
Followed instructions in https://discourse.gohugo.io/t/littlefoot-for-fancy-popup-footnotes/23991 to make footnotes more readable + easier to access in context.

### CODE REVIEW

**Comment by kodster28** [comment]
Open question... suggestion to download and host locally in [the thread](https://discourse.gohugo.io/t/littlefoot-for-fancy-popup-footnotes/23991) suggesting it.

What exactly does that mean?

**Comment by KianNH** [comment]
> Open question... suggestion to download and host locally in [the thread](https://discourse.gohugo.io/t/littlefoot-for-fancy-popup-footnotes/23991) suggesting it.
> 
> What exactly does that mean?



I think they mean that `https://unpkg.com` is sometimes a bottleneck - so the rest of your site has loaded but you're waiting on the library to download from their CDN, causing layout shift ( or whatever it does ).

It's [jsDelivr](https://www.jsdelivr.com/package/npm/littlefoot) as an alternative.

**Comment by kodster28** [comment]
Thanks for the context, @KianNH! 

From looking at Lighthouse testing comparisons, it _seems_ like there isn't any bottleneck. Once this goes live though, I'll keep an eye out and be ready to test other solutions as needed.

**Review by marciocloudflare — APPROVED** [review]

**Comment by kodster28** [comment]
Just closing the loop here, @KianNH, had to adjust the script slightly in #5338 , but it looks like it's good now

**Comment by KianNH** [comment]
The joys of webperf 🫠

When are we getting Early Hints too? :^)

**Comment by kodster28** [comment]
Oooh, good suggestion. Getting the Pages team to flip the switch for us (they're working on integrating them into Pages by default).

**Comment by KianNH** [comment]
I’m excited for it! I released a Worker to add them with HTMLRewriter and Obinna made a Pages plug-in from it - now we just need @WalshyDev to make it native ;)

**Comment by WalshyDev** [comment]
Enabled for docs and coming soon to a Pages site near you :^)

**Comment by KianNH** [comment]
What's the go-to for handling files with hashes in their name?

i.e the docs site has no `link` headers right now so there'll be no 103 responses but the JS uses a hash in the filename for cache busting

Can you add those to the `_headers` file post-build command and Pages will be fine with that? Guess we'd also want the `littlefoot` package in there too

**Comment by WalshyDev** [comment]
> Can you add those to the _headers file post-build command and Pages will be fine with that?

Yep. As long as they're there when we read the file (at publish step) it's all cool

**Comment by KianNH** [comment]
Maybe I'll PR something that isn't R2 or Workers for once

**Pull request merged**
