### PR TITLE
feat(CI): add a GitHub Action to check spelling

### PR DESCRIPTION
**Pull request by jbampton**
- Using https://github.com/client9/misspell
- Run only on pull request
- Pass in the -w flag to auto fix the incorrect spelling

refs #492 
refs #495 
refs #784 
refs #787

### CODE REVIEW

**Comment by haneefmubarak** [comment]
@jbampton could you please separate the GitHub Action and the spelling changes into 2 separate commits? Also could you rebase against `production` and resolve the conflicts?

Happy to merge after that, LGTM otherwise.

**Comment by jbampton** [comment]
Hey @haneefmubarak this one is ready for review now 👍

**Comment by jbampton** [comment]
Hey @haneefmubarak  I made a mistake and did 2 separate PRs instead of 2 commits :(

**Review by haneefmubarak — APPROVED** [review]

**Comment by haneefmubarak** [comment]
Nice, it caught a spelling mistake before even merging. Alright, I'll rebase and fixup later before merging.

**Comment by KimJ15** [comment]
👋 @jbampton Thank you for the feedback. We are hard at work on many things related to the deploy and build process, including a testing suite. Going forward, we are only taking care of doc contributions in this repo for developers.cloudflare.com!

**Pull request closed without merging**
