### PR TITLE
Add TURN credential creation

### PR DESCRIPTION
**Pull request by third774**

### CODE REVIEW

**Comment by third774** [comment]
Let's hold off on merging this, API might still change.

**Comment by kodster28** [comment]
> Let's hold off on merging this, API might still change.

Converted to a draft just to give more indication around that

**Review by renandincer — APPROVED** [review]

**Comment by third774** [comment]
Okay, I think we're good to go on this!

**Comment by third774** [comment]
@kodster28 any thoughts/feedback before we merge?

**Pull request merged**
