### PR TITLE
Add link to IATA code for `colo` in request docs

### PR DESCRIPTION
**Pull request by 12932**
A bit nit-picky but less ambiguous than "three letter airport code"

### CODE REVIEW

**Comment by adaptive** [comment]
That information is incorrect, ICAO code is 4 letters.

**Comment by 12932** [comment]
Oh you're right, I have changed it to IATA code instead

**Comment by kristianfreeman** [comment]
it seems like this is an IATA code, but i don't know for sure! cc @rita3ko who may know definitively

**Review by haneefmubarak — APPROVED** [review]
LGTM, squashing and merging.

**Pull request merged**
