### PR TITLE
[Workers] Fix Workers limits page

### PR DESCRIPTION
**Pull request by WalshyDev**
Fixed #2839 so it can deploy 

image

(Sorry for burning your eyes)

### CODE REVIEW

**Comment by WalshyDev** [comment]
cc: @Albertozhao @deadlypants1973

**Comment by Albertozhao** [comment]
> 

@deadlypants1973 Walshy helpfully closed a tag. Will merge once it gets your 👍

**Comment by vlovich** [comment]
I'd feel more comfortable if a PM or @kentonv reviewed this.

**Comment by Albertozhao** [comment]
> 

@vlovich Sorry for the confusion: the content of this PR was made by both me and @greg-mckeon. Walshy just saw the build failed because a missing `</Aside>` from the [original PR](https://github.com/cloudflare/cloudflare-docs/pull/2839) and only added that.

**Review by kristianfreeman — APPROVED** [review]

**Pull request merged**
