### PR TITLE
[Pulumi] Adds a new tutorial

### PR DESCRIPTION
**Pull request by desteves**
### Summary

This PR introduces a new Pulumi tutorial to cover how to configure Pulumi ESC (secrets management) with Wrangler commands. It slightly modifies the meta for the two existing Pulumi tutorial to accommodate this one.

### Documentation checklist

- [x] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.

### CODE REVIEW

**Comment by kodster28** [comment]
Hey hey @desteves, I'll take a look at this next week.

I'll need to port it over to our new framework + content locations (we _just_ moved to Starlight / Astro), which shouldn't take too long... but we're getting a lot of good feedback on the site that I have to prioritize.

Thanks for contributing!

**Comment by desteves** [comment]
That's great to hear; next week works :)

**Comment by desteves** [comment]
👋🏽 @kodster28 any updates on merging this item?

**Comment by kodster28** [comment]
> 👋🏽 @kodster28 any updates on merging this item?

Slipped off my mind... apologies!

Let me hop in right now

**Comment by kodster28** [comment]
Moved to #16617

**Pull request closed without merging**
