### PR TITLE
[Magic WAN] Correcting architecture description

### PR DESCRIPTION
**Pull request by bsimcloudflare**
PCX-11004

- Created new partial for Magic WAN from Magic Transit documentation (_tunnels-encapsulation-opening.md)
- Updated partial to more accurately represent Magic WAN architecture
- Updated tunnels.md to use new partial

### CODE REVIEW

**Comment by marciocloudflare** [comment]
Hi @bsimcloudflare. What do you want to update exactly? The whole purpose of the partial file is to make sure Magic Transit and Magic WAN share a single source of truth so content doesn't become outdated, and then change the details that are different for each product. You seem to have duplicated most of the content, which I fear will make both products grow outdated once again. Thanks!

**Comment by bsimcloudflare** [comment]
Hi @marciocloudflare, I created the new partial because there are some differences between how Magic WAN and Magic Transit tunnel traffic by default, which I have seen mislead customers and support personnel before. Magic WAN does not use Direct Server Return (DSR) by default, and is not a commonly used configuration at all. This is because Magic WAN traffic primarily uses private IP space, so DSR would not be possible. Additionally, most Magic WAN customers use IPsec tunnels, and GRE is not commonly seen. Because of this, I updated the diagram and the Aside to reflect this information.

Is there a better way for this to be done programmatically within the Magic Transit partial? I couldn't think of a good way to do it without the creation of a new short code. Let me know your thoughts.

**Comment by marciocloudflare** [comment]
Hi @bsimcloudflare . I'll have to think how we could address this with the way partials work right now. Could you create a PCX ticket with all the changes needed - what's different from MWAN to MT? Even if it's not possible right now, I'll see internally if there's anything we can do about partials to make them more flexible. In the meantime, I feel we should refrain from creating an entire new page while I try to address this in a more efficient way, to avoid a situation like the one we had in January 2023 where the pages had drifted apart, and both had outdated information scattered throughout them. Does this seem ok to you for now?

**Comment by bsimcloudflare** [comment]
Hi @marciocloudflare, I totally understand the concern. The PCX ticket is PCX-11004, I'll work on fleshing it out with some more details.

**Comment by marciocloudflare** [comment]
Closing this as the work is being continued in PCX ticket

**Pull request closed without merging**
