### PR TITLE
[Pages] Fix broken build-configuration.json

### PR DESCRIPTION
**Pull request by KianNH**

### CODE REVIEW

**Comment by WalshyDev** [comment]
We also need to change `layouts/shortcodes/pages-build-preset.html` and `layouts/shortcodes/pages-build-presets-table.html`

**Comment by KianNH** [comment]
https://patch-108.cloudflare-docs-github.pages.dev/

**Comment by KianNH** [comment]
Make sure...

- [x] https://patch-108.cloudflare-docs-github.pages.dev/pages/framework-guides/deploy-a-brunch-site/ has Build command / Build directory
- [x] https://patch-108.cloudflare-docs-github.pages.dev/pages/configuration/build-configuration/index.json renders
- [x] https://patch-108.cloudflare-docs-github.pages.dev/pages/configuration/build-configuration/ table renders

**Comment by kodster28** [comment]
Confirmed the fix works

**Review by kodster28 — APPROVED** [review]

**Review by WalshyDev — APPROVED** [review]

**Pull request merged**
