### PR TITLE
Update www-redirect.md

### PR DESCRIPTION
**Pull request by RyderCragie**
### Documentation checklist

- [ ] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

### CODE REVIEW

**Comment by kodster28** [comment]
@RyderCragie, just making sure I understand your suggestion.... is there an inherent advantage here to having the redirect happen for an AAAA vs A record?

In my understanding, both should work the same functionally b/c both just serve as "dummy" records to cover your specific hostname with a placeholder DNS record.

**Comment by RyderCragie** [comment]
I was told it's what Cloudflare now recommend instead, and it's also in some of the docs.

**Comment by kodster28** [comment]
> I was told it's what Cloudflare now recommend instead, and it's also in some of the docs.

Mind elaborating where you heard this? Discord / other locations?

**Comment by KimJ15** [comment]
👋Hi there, we’re going to close this PR. All PRs prior to August 12 need to be reworked due to the platform migration to Astro.

**Pull request closed without merging**
