### PR TITLE
re-add algolia

### PR DESCRIPTION
**Pull request by kristianfreeman**
wip

### CODE REVIEW

**Comment by kodster28** [comment]
Heyo, @codewithkristian, for the conflicts, can you just accept the incoming ones?

It's related to https://github.com/cloudflare/cloudflare-docs/pull/8348, which added some new functionality to the products grid.

**Comment by kodster28** [comment]
@codewithkristian, we actually still need the ability to trigger Coveo searches for a few specific scenarios... which I imagine is easier than re-building similar functionality in Algolia.

Scenarios:
- The current [Tutorials](https://developers.cloudflare.com/tutorials/) page, which is broken in the [preview](https://algolia.cloudflare-docs-7ou.pages.dev/tutorials/)
- The existing [search](https://developers.cloudflare.com/search/) page, which is linked to from the API docs, the [dashboard landing page](https://developers.cloudflare.com/dashboard-landing/), and the empty state of our newer [product grid](https://developers.cloudflare.com/products/).

**Review by kodster28 — CHANGES_REQUESTED** [review]
Blocked on the concerns mentioned about completely removing Coveo at this time.

We can strip those parts out fully in the future, but -- again -- it'd take a bit more work and time to get there.

**Review by kodster28 — COMMENTED** [review]
Coveo has been re-added correctly.

**Review by kodster28 — APPROVED** [review]

**Comment by Skye-31** [comment]
~~Seems to be a visual bug here~~ fixed now 🧡 
image

**Review by rita3ko — APPROVED** [review]

**Pull request merged**
