### PR TITLE
Deploy to Cloudflare Workers too

### PR DESCRIPTION
**Pull request by GregBrimble**
### Summary

This deploys the docs site to Workers too, available at https://cloudflare-docs.cloudflare-docs.workers.dev/.

Unfortunately, without faffing around with caching the static build and moving it around, I couldn't easily do something like `continue-on-error`, so left it here. If it's a concern, we can pull it out, no worries.

Things to test are: `/api`, 404 behavior, `_redirects` and regular docs browsing experience (e.g. images, styles, fonts, pages, trailing slashes, etc.)

### CODE REVIEW

**Comment by GregBrimble** [comment]
Oh, we want to restrict this to just running on `production`.

**Comment by kodster28** [comment]
> Oh, we want to restrict this to just running on `production`.

Ah, let me see if I can recall that syntax

**Comment by kodster28** [comment]
> > Oh, we want to restrict this to just running on `production`.
> 
> Ah, let me see if I can recall that syntax

Heyo @GregBrimble, think I did this correctly by following [the GitHub community hack](https://github.com/orgs/community/discussions/26349#discussioncomment-3251577).

**Comment by kodster28** [comment]
Appears to be working
image

**Comment by GregBrimble** [comment]
Beautiful, yeah, that looks good, thank you! Whilst I'm here, I've also just opted in to uploading versions on all non-production things too, so that we can test out the preview URLs.

**Review by kodster28 — APPROVED** [review]

**Pull request merged**
