### PR TITLE
[Calls / TURN] Add note about RTCPeerConnection structure

### PR DESCRIPTION
**Pull request by benfoxall**
### Summary

Maybe this doc change could be clearer, but here's the issue I was having:

I was stuck for quite a while trying to pass on turn credentials to an `RTCPeerConnection` via [y-webrtc](https://github.com/yjs/y-webrtc) & [simple-peer](https://github.com/feross/simple-peer), it seems that I was passing along the ice credentials incorrectly.

Here's how I ended up modifying the credentials:
```js
const TURN_ID = 'secret_id';
const TOKEN = 'secret_token';

// Fetch TURN credentials from the API (don't worry, I'm using a worker in the real thing!)
const response = await fetch(`https://rtc.live.cloudflare.com/v1/turn/keys/${TURN_ID}/credentials/generate`, {
  method: 'POST',
  headers: {
    'Authorization': `Bearer ${TOKEN}`,
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({ ttl: 86400 }),
});

// Parse the response
const config = await response.json();

try {
  // Attempt to create a new RTCPeerConnection using the returned config
  const pc = new RTCPeerConnection(config);
} catch (e) {
  // Error occurs here because config.iceServers is not iterable
  console.error('Error constructing RTCPeerConnection:', e);
  // Error message: TypeError: Failed to construct 'RTCPeerConnection': 
  // Failed to read the 'iceServers' property from 'RTCConfiguration': 
  // The object must have a callable @@iterator property.
}

// Fix the issue by wrapping iceServers in an array
config.iceServers = [config.iceServers]; // Ensure iceServers is an array

try {
  // Attempt to create the RTCPeerConnection again with the fixed config
  const pc = new RTCPeerConnection(config);
  console.log('RTCPeerConnection successfully created.');
} catch (e) {
  // This block won't be called as the iceServers issue has been resolved
  console.error('Unexpected error constructing RTCPeerConnection:', e);
}
```

### Documentation checklist

- [x] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [x] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [x] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

### CODE REVIEW

**Comment by KimJ15** [comment]
@dcpena reassigning this PR to you.

**Comment by nils-ohlmeier** [comment]
I think the pseudo code already shows an array. And as far as I can remember the change for iceServers (not the plural here) to be an array is quite old, see https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection#browser_compatibility

The word 'now' suggests to me that this is something new, which I don't think is the case. If we remove the word 'now' from the PR I have no problem with the extra hint about it being an array.

@renandincer what do you think?

**Comment by renandincer** [comment]
let's ship it! thanks for the contribution @benfoxall

**Review by renandincer — APPROVED** [review]

**Comment by benfoxall** [comment]
>  the word 'now' 

I meant this as in "it was an object in the credential response, but now it's an array", tbh the wording isn't that great, but thanks for merging 😅

**Pull request merged**
