### PR TITLE
refactor: enable MD022 Headers should be surrounded by blank lines

### PR DESCRIPTION
**Pull request by jbampton**

### CODE REVIEW

**Review by lukevalenta — APPROVED** [review]
Confirmed this change only adds blank lines. Approving time-services changes.

**Review by bkrebsbach — APPROVED** [review]
LGTM, approving Stream changes.

**Comment by haneefmubarak** [comment]
LGTM: approving Workers changes.

**Review by haneefmubarak — APPROVED** [review]

**Comment by KimJ15** [comment]
👋 @jbampton Thank you for the feedback. We are hard at work on many things related to the deploy and build process, including this. Going forward, we are only taking care of doc contributions in this repo for developers.cloudflare.com!

**Pull request closed without merging**
