### PR TITLE
Configure Token Auth move /support/

### PR DESCRIPTION
**Pull request by jedecf**
Move: https://developers.cloudflare.com/support/firewall/learn-more/configuring-token-authentication/#implement-token-creation with redirect

### CODE REVIEW

**Comment by kodster28** [comment]
Maybe a broader question for @pedrosousa, is this content still relevant / useful?

**Comment by pedrosousa** [comment]
Yes, it's still useful. I believe there are some repeated examples we can refactor, but the token generation examples are still relevant.

**Review by pedrosousa — CHANGES_REQUESTED** [review]
Requesting changes to prevent a merge before we update the Workers HMAC token auth example (to be addressed very soon).

Update: Waiting on @penalosa's contribution to update the Workers example, which should happen in Jan 2024.

**Comment by pedrosousa** [comment]
The Workers example was updated in #12466. We can now go ahead with this PR.

**Review by pedrosousa — APPROVED** [review]

**Pull request merged**
