### PR TITLE
Update remote-management.mdx

### PR DESCRIPTION
**Pull request by adegoodyer**
Updated instructions to create systemd service for linux.
  - use sensible log location
  - add [install] section so service can be enabled
  - add systemctl commands to enable and start service
  - add system log command to debug any potential issues

### Documentation checklist

- [ ] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

### CODE REVIEW

**Comment by ranbel** [comment]
Hey @adegoodyer, thanks for the PR. The commands shown in the remote tunnel dashboard flow should automatically create and enable `cloudflared.service`. Therefore, the instructions are oriented towards updating the existing `cloudflared.service` file. May I ask why you needed to create `cloudflared.service` from scratch?

**Comment by adegoodyer** [comment]
Hi @ranbel. Yes certainly, was building an Linux container (well lxc) running gotify on Proxmox. Wasn't sure if the service was enabled to start automatically when restarted, so enabled it explicitly to make sure.

The log path is a sensible location for that os and the other commands are just additional extras.

I thought it might help others, but feel free to amend or reject if not useful or in line with the workflow.

**Comment by ranbel** [comment]
Tested out the remote tunnel configuration steps and confirmed that the docs were missing a restart command. Thanks for the suggestions!

**Review by ranbel — APPROVED** [review]

**Comment by adegoodyer** [comment]
> Tested out the remote tunnel configuration steps and confirmed that the docs were missing a restart command. Thanks for the suggestions!

@ranbel You're most welcome! In future I'll shape the PR more in line with Cloudflare paradigms and provide more evidence of the testing I did to save a bit of work your end.

**Pull request merged**
