### PR TITLE
[Doc site]: Add copy to clipboard for code snippets

### PR DESCRIPTION
**Pull request by Ekwuno**
This PR adds copy to clipboard functionality for our code snippets. 
Screen Recording 2022-08-03 at 13 04 46

eg: 
https://copy-to-clipboard.cloudflare-docs-7ou.pages.dev/pages/platform/functions

### CODE REVIEW

**Comment by rita3ko** [comment]
@Ekwuno it looks like the button is in active state by default: 
Screen Shot 2022-08-03 at 8 31 14 AM

It should be light gray when it's not pressed and become dark gray when you hover IMO. can you update?

**Review by rita3ko — APPROVED** [review]

**Comment by WalshyDev** [comment]
I'd love to get feedback from @Cherry regarding design and accessibility

**Comment by Ekwuno** [comment]
@Cherry come check this out!

**Review by Cherry — COMMENTED** [review]
Thanks for the ping! This looks generally great, and the accessibility of the button works well! 🧡

My one comment would be in regards to a lack of any confirmation state that the code was actually copied. After I activate the button, it's not clear that anything actually happened. A common solution to this on the web is some kind of toast or notification. Here's a few examples:

- Google Translate: https://up.jross.me/kv902sg5
- NPM: https://up.jross.me/iem240pp
- Netlify docs: https://up.jross.me/k8o8m0pp

They're all slightly different, but each make it clear that something happened.

**Comment by Ekwuno** [comment]
@Cherry, I addressed the call to action. Thank you so much.

**Comment by pedrosousa** [comment]
When using the dark theme, the button icon is barely visible unless you hover it... I'm not sure if something changed in terms of CSS.
copy-button-hover

**Comment by Cherry** [comment]
> @Cherry, I addressed the call to action. Thank you so much.

This looks great, thanks @Ekwuno! It appears to only be visible if I'm using a mouse though. If I tab to the copy button with my keyboard and then hit `enter` to activate it, there's no confirmation.

**Comment by Ekwuno** [comment]
> > @Cherry, I addressed the call to action. Thank you so much.
> 
> This looks great, thanks @Ekwuno! It appears to only be visible if I'm using a mouse though. If I tab to the copy button with my keyboard and then hit `enter` to activate it, there's no confirmation.
Added!

**Comment by pedrosousa** [comment]
~A lingering issue that seems to affect only the Windows platform (tested in both Chrome and Firefox) in one-line code blocks will be handled in a separate PR. Approving because this is not a blocking issue.~
Update: @Ekwuno solved the remaining issue.

**Review by pedrosousa — APPROVED** [review]

**Pull request merged**
