### PR TITLE
Add Authenticated GCS Origin Support

### PR DESCRIPTION
**Pull request by kyouheicf**
I have confirmed with these code `image-resizing-private-gcs.js`
https://github.com/kyouheicf/private-access-to-gcs

### CODE REVIEW

**Comment by sejoker** [comment]
this is not supported as it requires handling  x-goog-* headers on the Cloudflare side.
per https://cloud.google.com/storage/docs/migrating.

**Comment by dcpena** [comment]
Thanks for clarifying @sejoker. 

@kyouheicf, I'm going to close this PR as this isn't supported.

**Comment by kyouheicf** [comment]
@sejoker @dcpena Using HMAC authentication, I have confirmed that it's working.
Actually the signed request header only contains `Authorization`, `x-amz-content-sha256`, `x-amz-date` header.
I don't understand why it's not supported yet. Can you confirm using my code?

**Comment by sejoker** [comment]
this is fine to merge, @dcpena please reopen PR.

**Review by dcpena — APPROVED** [review]

**Pull request merged**
