### PR TITLE
Create libraries.md

### PR DESCRIPTION
**Pull request by bofrost007**
I've added all the tools shown in the CF dashboard as of today

### CODE REVIEW

**Comment by marciocloudflare** [comment]
Can I ask what made you create this page @bofrost007 ? Is this something customers are asking for? As it is, this page only replicates what customers can already see in the dash. I'm worried that from a maintenance perspective this will be out of date quickly. Thanks!

**Comment by bofrost007** [comment]
Hi @marciocloudflare,
I understand your concern. I received the question about the integration and my first way was to the docs page (as always) but it wasn't shown there.
Additionally, if you are not a CF customer right now and you want to validate if Zaraz is supporting your tools, you can't without creating a CF account first.
Keep in mind, Zaraz is not only for websites proxied through Cloudflare

**Comment by marciocloudflare** [comment]
Thanks for that update @bofrost007. I'll talk to the PM regarding your idea. But I think there's an internal Wiki with this info, which might be a better way of addressing your concern.

**Comment by marciocloudflare** [comment]
Hey @bofrost007. There are a few things missing from this PR that we need on our pages. I'm going to copy this, and create a new PR with the appropriate frontmatter missing, along with some corrections regarding to style. Thanks!

**Pull request closed without merging**
