### PR TITLE
Change dev to use wrangler

### PR DESCRIPTION
**Pull request by WalshyDev**
Currently, we use the in-built Hugo dev which is fine but it means things like redirects, headers and Functions don't work. To better emulate prod we should instead be using Wrangler.
This PR changes it to run `wrangler pages dev public` and `hugo --watch`. This means any doc changes are still watched and updated + we also support all the Pages goodies

### CODE REVIEW

**Comment by kodster28** [comment]
I'll put aside a bit of time tomorrow to test this out. Thanks!!

**Comment by kodster28** [comment]
Did a touch of testing and the `dev:wrangler` works fine.

Ran into a few weird issues with the first couple builds of `npm run dev` and `npm run dev:hugo`, but things seem to be mostly fine after I deleted the `public` folder.

One thing we'd be losing though would be the live reload functionality that happens every time you save changes to a .md file. Is there a way to have that still work with this implementation?

**Comment by WalshyDev** [comment]
> Ran into a few weird issues with the first couple builds of npm run dev and npm run dev:hugo, but things seem to be mostly fine after I deleted the public folder.

Oh really? What kinda issues did you see?
There's an issue with Wrangler right now which is being tracked here: https://github.com/cloudflare/wrangler2/issues/2638  

> One thing we'd be losing though would be the live reload functionality that happens every time you save changes to a .md file. Is there a way to have that still work with this implementation?

Should still work, `hugo --watch` will watch for those changes. It should put the updated file in `public` which then triggers `wrangler pages dev` to reload... however, I can verify Wrangler not reloading. Doing a manual reload does show the updated file, I wonder why we aren't seeing it 🤔

**Comment by pedrosousa** [comment]
Tested on Windows. Also had to reload each updated page to see my local changes.

Additionally, I got a bunch of errors when running `yarn dev` (below). I immediately got the errors described in https://github.com/cloudflare/wrangler2/issues/2638 without making any changes to `_headers` or `_redirects`.

I had to go to the documentation to find the `localhost:8788` hostname and port, since it's not part of the output!

```
λ yarn dev
yarn run v1.22.17
$ concurrently npm:dev:*
[wrangler]
[wrangler] > cloudflare-docs@1.0.0 dev:wrangler
[wrangler] > wrangler pages dev public
[wrangler]
[hugo]
[hugo] > cloudflare-docs@1.0.0 dev:hugo
[hugo] > hugo --watch
[hugo]
[wrangler] ▲ [WARNING] It looks like you have used Wrangler 1's `config` command to login with an API token.
[wrangler]
[wrangler]   This is no longer supported in the current version of Wrangler.
[wrangler]   If you wish to authenticate via an API token then please set the `CLOUDFLARE_API_TOKEN` environment variable.
[wrangler]
[wrangler]
[wrangler] � 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose [wrangler] ▲ [WARNING] No compatibility_date was specified. Using today's date: 2023-01-31.
[wrangler]
[wrangler]   Pass it in your terminal:
[wrangler]   ```
[wrangler]   --compatibility-date=2023-01-31
[wrangler]   ```
[wrangler]   See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more information.
[wrangler]
[wrangler]
[wrangler] Compiling worker to "C:\Users\PEDROS~1\AppData\Local\Temp\functionsWorker-0.29919637021154344.mjs"...
[wrangler] ✨ Compiled Worker successfully
[hugo] Start building sites ...
[hugo] hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended windows/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
[wrangler] Debugger listening on ws://127.0.0.1:55007/912bce6a-7f0d-4e6d-b492-804873fd7b76
[wrangler] For help, see: https://nodejs.org/en/docs/inspector
[wrangler] Debugger attached.
[wrangler] [pages:wrn] Parsed 1020 valid redirect rules.
[wrangler] [pages:wrn] Parsed 1 valid header rule.
[wrangler] [pages:wrn] Service bindings are experimental. There may be breaking changes in the future.
[wrangler] _headers modified. Re-evaluating...
[wrangler] [pages:err] Unhandled Promise Rejection: TypeError: Cannot read properties of undefined (reading 'logWithLevel')
[wrangler]     at warn (C:\docs\cloudflare-docs\node_modules\@miniflare\shared\src\log.ts:90:10)
[wrangler]     at constructRedirects (file:///C:/docs/cloudflare-docs/node_modules/wrangler/miniflare-dist/index.mjs:5654:3)
[wrangler]     at createMetadataObject (file:///C:/docs/cloudflare-docs/node_modules/wrangler/miniflare-dist/index.mjs:5639:8)
[wrangler]     at FSWatcher.<anonymous> (file:///C:/docs/cloudflare-docs/node_modules/wrangler/miniflare-dist/index.mjs:6112:18)
[wrangler]     at FSWatcher.emit (node:events:513:28)
[wrangler]     at FSWatcher.emit (node:domain:489:12)
[wrangler]     at FSWatcher.emitWithAll (C:\docs\cloudflare-docs\node_modules\chokidar\index.js:540:8)
[wrangler]     at FSWatcher._emit (C:\docs\cloudflare-docs\node_modules\chokidar\index.js:632:8)
[wrangler]     at listener (C:\docs\cloudflare-docs\node_modules\chokidar\lib\nodefs-handler.js:370:20)
[wrangler] _redirects modified. Re-evaluating...
[wrangler] [pages:err] Unhandled Promise Rejection: TypeError: Cannot read properties of undefined (reading 'logWithLevel')
[wrangler]     at warn (C:\docs\cloudflare-docs\node_modules\@miniflare\shared\src\log.ts:90:10)
[wrangler]     at constructRedirects (file:///C:/docs/cloudflare-docs/node_modules/wrangler/miniflare-dist/index.mjs:5654:3)
[wrangler]     at createMetadataObject (file:///C:/docs/cloudflare-docs/node_modules/wrangler/miniflare-dist/index.mjs:5639:8)
[wrangler]     at FSWatcher.<anonymous> (file:///C:/docs/cloudflare-docs/node_modules/wrangler/miniflare-dist/index.mjs:6112:18)
[wrangler]     at FSWatcher.emit (node:events:513:28)
[wrangler]     at FSWatcher.emit (node:domain:489:12)
[wrangler]     at FSWatcher.emitWithAll (C:\docs\cloudflare-docs\node_modules\chokidar\index.js:540:8)
[wrangler]     at FSWatcher._emit (C:\docs\cloudflare-docs\node_modules\chokidar\index.js:632:8)
[wrangler]     at listener (C:\docs\cloudflare-docs\node_modules\chokidar\lib\nodefs-handler.js:370:20)
[hugo]
[hugo]                    |  EN
[hugo] -------------------+-------
[hugo]   Pages            | 2853
[hugo]   Paginator pages  |    0
[hugo]   Non-page files   | 1480
[hugo]   Static files     |   52
[hugo]   Processed images |    0
[hugo]   Aliases          |    0
[hugo]   Sitemaps         |    1
[hugo]   Cleaned          |    0
[hugo]
[hugo] Watching for changes in C:\docs\cloudflare-docs\{assets,content,data,layouts,package.json,static}
[hugo] Press Ctrl+C to stop
[hugo] Watching for config changes in C:\docs\cloudflare-docs\config.toml
```

Given the non-ideal dev experience at the moment, we should probably wait a bit longer before merging.

Edit: Forgot to mention that I never got `concurrently` to work properly on Windows... There's always some leftover process still running (wrangler, npm, or Hugo) after pressing `Ctrl+C`, which may cause errors when running `yarn dev` again (e.g., `Error: listen EADDRINUSE: address already in use 0.0.0.0:8788`).

**Pull request closed without merging**
