### PR TITLE
Version error info added

### PR DESCRIPTION
**Pull request by fre2mansur**
npm update -g @cloudflare/wrangler

npm warn deprecated @cloudflare/wrangler@1.21.0: This package is for Wrangler v1.x  and is no longer supported. Please visit https://www.npmjs.com/package/wrangler for Wrangler v2+.

### Documentation checklist

- [ ] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

### CODE REVIEW

**Comment by dario-piotrowicz** [comment]
Hi @fre2mansur, thanks for the PR

However the page seems to already include quite an evident warning message regarding the v1 package being deperecated: https://developers.cloudflare.com/workers/wrangler/migration/v1-to-v2/wrangler-legacy/install-update/

Screenshot 2024-10-29 at 20 15 31

Could you explain why you'd propose adding again the same sort of information?

Am I missing something?

**Comment by fre2mansur** [comment]
Yes, the warning is there, but there is no link for the documentation for v2.

**Comment by ToriLindsay** [comment]
I updated the Warning message instead, to make it more clear. I don't think we should call out v2 by name to keep it from getting outdated when later versions are released, but hopefully this will help. Thank you @fre2mansur !

**Review by Oxyjun — APPROVED** [review]

**Comment by ToriLindsay** [comment]
cc: @dario-piotrowicz

**Pull request merged**
