### PR TITLE
[workers-ai] Fixes and copy on RAG tut

### PR DESCRIPTION
**Pull request by kristianfreeman**
Thanks @KianNH for surfacing

### CODE REVIEW

**Comment by KianNH** [comment]
There's an incorrect `index = "vector-index"` in the `vectorize` binding (should be `index_name`) which might be worth fixing whilst we're already here.

**Comment by kristianfreeman** [comment]
thanks, fixed!

**Comment by KianNH** [comment]
The `[[ai]]` looks like it should be `[ai]` too (not an array).

**Comment by KianNH** [comment]
The Hono examples (which people might copy/paste) are missing `import { Ai } from '@cloudflare.com/ai'`, and it would be cool for Tab Switcher & TS examples (mainly to show people how to use TS with Hono, really) but that might be a thing for a second pass PR.

**Review by irvinebroque — APPROVED** [review]

**Pull request merged**
