### PR TITLE
Update _index.html

### PR DESCRIPTION
**Pull request by RyderCragie**
Changed Discord URL to discord.cloudflare.com, and changed the Twitter URL to x.com.

### CODE REVIEW

**Comment by RyderCragie** [comment]
Review

**Review by kodster28 — APPROVED** [review]

**Comment by kodster28** [comment]
Thanks @RyderCragie! Also, need to review your other two PRs from last week :)

**Comment by RyderCragie** [comment]
Thanks @kodster28. Any issues with them just let me know. Not very good at coding or working with GitHub so if it's wrong just let me know and I can amend.

**Comment by RyderCragie** [comment]
@kodster28, where's the repository for https://pages.cloudflare.com? Spotted some issues there too.

**Pull request merged**
