### PR TITLE
Testing adding rel preload headers

### PR DESCRIPTION
**Pull request by kodster28**
Addresses #5348 .

From looking at [this thread](https://stackoverflow.com/questions/46787921/rel-preload-for-stylesheet-isnt-applying-the-styles-once-downloaded)... seems acceptable to have two `rel` attributes to actually apply the spreadsheet.

### CODE REVIEW

**Comment by kodster28** [comment]
@GregBrimble, not sure if you had any thoughts on the implementation? i.e., which of the approaches works best (2 `rel` links, two stylesheet declarations, having a `onload="this.rel='stylesheet'"` property... or maybe something I'm not thinking of.

Just swapping to the `rel=preload as="style"` doesn't apply the stylesheet to the page.

**Comment by kodster28** [comment]
Definitely does speed up the homepage load...

Original
Screen Shot 2022-10-07 at 11 53 51 AM

Preload headers
Screen Shot 2022-10-07 at 11 53 43 AM

Preconnect headers
Screen Shot 2022-10-10 at 9 10 32 AM

**Comment by GregBrimble** [comment]
Nifty! Adding two `rel` values together in the same `<link>` element isn't currently supported for [the recently announced automatic Pages and Early Hints integration](https://blog.cloudflare.com/early-hints-on-cloudflare-pages/), but it probably could be.

I think basically we need to change [this line](https://github.com/cloudflare/wrangler2/blob/main/packages/pages-shared/asset-server/handler.ts#L328) to be:

```diff
- .on("link[rel=preconnect],link[rel=preload]", {
+ .on("link[rel~=preconnect],link[rel~=preload]", {
```

**Comment by GregBrimble** [comment]
Looks like HTMLRewriter is actually a bit picky here (you could possibly call this a bug with HTMLRewriter?):

https://cloudflareworkers.com/#ef343d99a11b6bf64a7b684577c62427:https://tutorial.cloudflareworkers.com/

The attribute order changes how these selectors work. In summary:

- `rel="stylesheet preconnect"` ✅
- `rel="preconnect stylesheet"` ✅
- `rel="preconnect" rel="stylesheet"` ✅
- `rel="stylesheet" rel="preconnect" ` ❌

**Comment by GregBrimble** [comment]
image

[W3C](https://validator.w3.org/nu/) doesn't like two of the same attributes, but it's fine with one attribute with two whitespace-separated values! So I'd say you should probably change to that, and we'll look at making that change to the Early Hints stuff :)

**Review by pedrosousa — APPROVED** [review]

**Pull request merged**
