### PR TITLE
[Docs-site]: Fix behaviour for multiple tab switcher

### PR DESCRIPTION
**Pull request by Ekwuno**
This PR addresses #5319

Co-authored-by: Daniel Walsh  @WalshyDev

### CODE REVIEW

**Comment by KianNH** [comment]
:goat: 

Edit: it's supposed to be GOAT but GitHub's emojis suck

**Comment by Ekwuno** [comment]
@WalshyDev is the G.O.A.T!!

**Review by WalshyDev — APPROVED** [review]
Just cleaned up the diff a bit and validated this still works nicely. Let's ship 🚢

**Comment by Ekwuno** [comment]
🚢 ⛴🚚

**Pull request merged**
