### PR TITLE
fix: update the rust worker get started

### PR DESCRIPTION
**Pull request by ghostdevv**
### Summary

Based on the [cloudflare/workers-rs](https://github.com/cloudflare/workers-rs) readme and [tutorials/workers-kv-from-rust](https://developers.cloudflare.com/workers/tutorials/workers-kv-from-rust)

### Documentation checklist

- [x] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [x] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [x] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

### CODE REVIEW

**Review by kodster28 — APPROVED** [review]

**Comment by mikenomitch** [comment]
This looks good functionality-wise, but I want to make sure that we prefer cargo to c3. IMO it makes sense to prefer cargo so we don't force npm on people who prefer the Rust ecosystem, but I want to make sure since I think we're pointing other Worker users towards C3.

@zebp, you +1 on pointing people towards cargo by default?

(edit: actually @kflansburg is prob best person to ask here)

**Comment by kflansburg** [comment]
> This looks good functionality-wise, but I want to make sure that we prefer cargo to c3. IMO it makes sense to prefer cargo so we don't force npm on people who prefer the Rust ecosystem, but I want to make sure since I think we're pointing other Worker users towards C3.
> 
> @zebp, you +1 on pointing people towards cargo by default?
> 
> (edit: actually @kflansburg is prob best person to ask here)

Yes, using Cargo was intentional and is preferred.

**Comment by ghostdevv** [comment]
> so we don't force npm on people who prefer the Rust ecosystem

 I think they need to anyway for wrangler but I get what you mean

**Comment by kodster28** [comment]
From this convo, assuming that this is fine to merge in?

**Comment by mikenomitch** [comment]
@kodster28 - merge away!

**Pull request merged**
