### PR TITLE
How to use objects with multiple environments

### PR DESCRIPTION
**Pull request by janat08**

### CODE REVIEW

**Comment by koeninger** [comment]
Please clarify on https://github.com/cloudflare/wrangler/issues/2142 exactly what your wrangler.toml contains, what commands you are running, and what output you are seeing. 

I just now tested the syntax for environment specific durable object bindings described by Domen on that issue for wrangler 1, and it works.

Raising a documentation PR saying that it is "bugged" is premature at this point.

**Comment by janat08** [comment]
I also added domens syntax to the docs, the bug is in the fact that the documented behavior doesn’t lead to expected results.

**Comment by janat08** [comment]
I’d rather reopened the issue and edit that to that syntax for that presumably may change.

**Comment by koeninger** [comment]
I can open a docs PR clarifying how wrangler environments interact with durable objects.  If you are seeing unexpected behavior, please clarify on the linked wrangler issue.

**Comment by janat08** [comment]
ty

**Pull request closed without merging**
