### PR TITLE
Renamed "How To" to "Framework Guides" in Pages doc

### PR DESCRIPTION
**Pull request by deadlypants1973**

### CODE REVIEW

**Comment by rita3ko** [comment]
One thing to keep in mind for this one is that we'll need to set up redirects. CC @signalnerve

**Review by crwaters16 — APPROVED** [review]
Approved now that redirects set up in https://github.com/cloudflare/cloudflare-docs/pull/1344.

**Comment by lukeed** [comment]
Maybe should find a new home for [`products/pages/src/content/framework-guides/npm-private-registry.md`](https://developers.cloudflare.com/pages/how-to)? It's the only one that doesn't fit, but got away with it under the "How To" umbrella

**Comment by kristianfreeman** [comment]
> Maybe should find a new home for [`products/pages/src/content/framework-guides/npm-private-registry.md`](https://developers.cloudflare.com/pages/how-to)? It's the only one that doesn't fit, but got away with it under the "How To" umbrella

probably can go in platform - `/pages/platform/npm-private-registry`

**Comment by rita3ko** [comment]
we could have a "Framwork Guides" section and a "How-to"s section for things like the NPM  packages which is not quite a tutorial but has nothing to do with frameworks. 
Another example of something that  could go there is: "Setting up  a www  redirect"

**Comment by lukeed** [comment]
Both sound good to me 👍

**Review by lukeed — APPROVED** [review]
This is ready to go 💪 Needed to be force pushed because there was some weird detached head stuff going on that @deadlypants1973 and I fixed together

Missing redirects for all framework guide URLs, which will happen later post-deploy.

**Pull request merged**
