### PR TITLE
fix(content): s/IPNS/IPFS

### PR DESCRIPTION
**Pull request by almndbtr**
## Summary

This fixes a typo by updating IPNS to IPFS.

### CODE REVIEW

**Review by thibmeu — APPROVED** [review]

**Comment by kodster28** [comment]
We'll need to wait to merge this until later today or Monday due to ongoing maintenance on the docs engine.

**Comment by lukevalenta** [comment]
I don't believe this is a typo. `IPNS` stands for InterPlanetary Name System (https://docs.ipfs.io/concepts/ipns/) is discussed in the linked article. It's probably fine either way though, especially given that 'Fission IPFS' is mentioned in the same sentence.

**Comment by crwaters16** [comment]
Thanks @almndbtr! Fixed in https://github.com/cloudflare/cloudflare-docs/pull/3626

**Comment by almndbtr** [comment]
@lukevalenta Oh my goodness, I totally learned something new and missed that in my own review! Sorry about that. Would you like to either revert this, or have me elaborate that specific detail in a follow up PR? I want to be a good citizen here!

**Comment by lukevalenta** [comment]
Hey @almndbtr no worries! I think the PR is probably still technically correct since IPNS could be considered a subsystem of IPFS. We don't mention IPNS directly elsewhere in the Cloudflare docs from what I can tell, so I'm on board with keeping the changes as-is. Thanks for the PR!

**Comment by almndbtr** [comment]
@lukevalenta - Thanks for the clarification. If you or the team change your minds, let me know! Totally happy to do follow-up work. Stay awesome ✨

**Pull request closed without merging**
