### PR TITLE
refactor: add blank lines around code blocks

### PR DESCRIPTION
**Pull request by jbampton**
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md031---fenced-code-blocks-should-be-surrounded-by-blank-lines

### CODE REVIEW

**Comment by kristianfreeman** [comment]
generally in favor of this, i can say for the workers portion of the codebase that this looks 👍  that being said, there's a ton of people that would need to review this for it to be merged in, but a +1 from me at least!

**Review by wbl — APPROVED** [review]

**Review by soheiokamoto — APPROVED** [review]

**Review by thibmeu — APPROVED** [review]
Changes are fine for Distributed web part

**Review by annikagarbers — APPROVED** [review]
MT section lgtm

**Review by bkrebsbach — APPROVED** [review]

**Review by abracchi-tw — APPROVED** [review]

**Review by haneefmubarak — APPROVED** [review]
Looks good for workers.

**Comment by haneefmubarak** [comment]
Merging in a week if no one raises any other concerns.

**Review by Everlag — APPROVED** [review]
Stream changes LGTM

**Review by migueldemoura — APPROVED** [review]

**Comment by KimJ15** [comment]
@jrf0110 Is this a PR we want to prioritize? There are several conflicts at this point so i'm not sure what your thoughts are.

**Comment by jrf0110** [comment]
Given that this PR is old and there are quite a few conflicts, I'm closing. Feel free to re-open with conflicts resolved

**Pull request closed without merging**
