### PR TITLE
Update Page Shield changelog of recent releases

### PR DESCRIPTION
**Pull request by xmflsct**
cc @pedrosousa

### CODE REVIEW

**Comment by kodster28** [comment]
Probs should include associated doc update for the Cookie Monitor part?

**Comment by pedrosousa** [comment]
> Probs should include associated doc update for the Cookie Monitor part?

Still being finalized. We can either wait for the docs to include that specific changelog entry, or just add the link later.

**Comment by xmflsct** [comment]
> > Probs should include associated doc update for the Cookie Monitor part?
> 
> Still being finalized. We can either wait for the docs to include that specific changelog entry, or just add the link later.

Let's wait for the docs. :)

**Comment by pedrosousa** [comment]
This PR will be updated and merged after #15165.

**Review by pedrosousa — APPROVED** [review]

**Pull request merged**
