### PR TITLE
Format the repo

### PR DESCRIPTION
**Pull request by vicb**
This PR formats the repo (`pnpm format`).

The rationale is that when I create a PR to this repo and want to format the code, I would run `pnpm format` but because the command fixes all the files in the repo, the PR include will include changes to file I have not updated (that is all the files formatted in this PR).

After the PR, running `pnpm format` will not add noise to PRs.

Note: I have added a few exclusions in `.prettierignore` as I don't think it makes sense to format those json files.

/cc @ToriLindsay

### CODE REVIEW

**Comment by ToriLindsay** [comment]
> /cc @ToriLindsay

I'm not sure I'm the right person to review this, but I'm finding out who is.

**Comment by vicb** [comment]
rebased.

**Review by KianNH — APPROVED** [review]

**Comment by ToriLindsay** [comment]
@vicb Kian approved this so it's good to merge when you're ready.

**Comment by vicb** [comment]
Thanks @ToriLindsay and @KianNH 🙏

**Comment by Cherry** [comment]
I had a lot of this in https://github.com/cloudflare/cloudflare-docs/pull/17262, but looks like this one was merged first. I've updated my PR to reflect this.

**Pull request merged**
