### PR TITLE
Update azuread.md

### PR DESCRIPTION
**Pull request by justin-chizer**
### Summary

Azure AD is now Microsoft Entra ID

### Documentation checklist

- [x] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

### CODE REVIEW

**Comment by maxvp** [comment]
Hi @justin-chizer, as mentioned on #16054, we are tracking this issue elsewhere. References to Azure AD in the docs will be updated soon.

**Comment by justin-chizer** [comment]
> Hi @justin-chizer, as mentioned on #16054, we are tracking this issue elsewhere. References to Azure AD in the docs will be updated soon.
Hey @maxvp, thank you for the reply. I placed quite a large bet on Cloudflare for my company. So when I have my team look at the Cloudflare docs and it still says Azure AD instead of Microsoft Entra it reflects poorly on me. It makes it look like I picked a vendor that doesn't care about Azure. It has been over a year since Microsoft made the name change. I'd like to know why there is such a delay in the documentation?

**Comment by maxvp** [comment]
> > Hi @justin-chizer, as mentioned on #16054, we are tracking this issue elsewhere. References to Azure AD in the docs will be updated soon.
> > Hey @maxvp, thank you for the reply. I placed quite a large bet on Cloudflare for my company. So when I have my team look at the Cloudflare docs and it still says Azure AD instead of Microsoft Entra it reflects poorly on me. It makes it look like I picked a vendor that doesn't care about Azure. It has been over a year since Microsoft made the name change. I'd like to know why there is such a delay in the documentation?

Hi @justin-chizer, we update our docs to follow the dashboard. I've gone ahead and updated references to Azure AD to Entra ID (tracked at PR #16997). I've also escalated the work to update the dashboard name to the proper engineering teams. I apologize for any inconvenience.

**Comment by kennyj42** [comment]
Hi Justin, I'm on the product team for Cloudflare's identity integrations. We are close and committed partners with Microsoft and are continuing to invest in the integration. We are happy to provide more info through your account team about this if you'd like.

We have been working on adding additional functionality to the Entra/AzureAd integration over the last year including Conditional Access synchronization and better SCIM support.

We're hoping to complete the renaming soon, but it requires migration work across Docs, the dashboard and API and we want to ensure we do it safely. I completely understand the frustration/appearance as well!

**Pull request closed without merging**
