### PR TITLE
provd quick typo correction

### PR DESCRIPTION
**Pull request by nleite**
typo correction: provide

### CODE REVIEW

**Review by Nuttapon43 — COMMENTED** [review]
@nleite

**Review by WalshyDev — APPROVED** [review]

**Comment by Nuttapon43** [comment]
@nleite @Nuttapon43

**Review by Nuttapon43 — COMMENTED** [review]
@nleite

**Review by Nuttapon43 — COMMENTED** [review]
https://github.com/martin-traverse/vcpkg/pull/1#issue-1435857435
@nleite @Nuttapon43

**Pull request merged**
