### PR TITLE
SPM-2190: Clarify the expected process for maintenance

### PR DESCRIPTION
**Pull request by ricardomacas**
- Corrects text implying an incident for every maintenance (our network is anycast+self-resilient)
- Adds text indicating expectations for customers of CNI
- Renames the section to "Disruptive Maintenance" in general, to better reflect the content: announced maintenances are to notify customers of disruption (i.e. they are disruptive by definition), and it covers both "Scheduled" and "Unscheduled" maintenances.

### CODE REVIEW

**Comment by ngayerie** [comment]
The content itself look good!
But @jedecf could you please review this PR in regards to the pages organization?
Do we need to set up a redirect here as a page is being deleted?

**Comment by kodster28** [comment]
> The content itself look good! But @jedecf could you please review this PR in regards to the pages organization? Do we need to set up a redirect here as a page is being deleted?

Yes, redirects are needed in this case

**Comment by ricardomacas** [comment]
I have found that I had mentioned two internal links that I had not properly added. I have corrected this in the last commit.

**Comment by ricardomacas** [comment]
@kodster28 and @ngayerie - added the redirects as requested

**Comment by ricardomacas** [comment]
fixed broken link in /notifications/ showing as error in the previous build

**Comment by ricardomacas** [comment]
All checks are passing, let me know if any changes are needed.

**Comment by ngayerie** [comment]
@jedecf may I let you review and merge please?

**Comment by ricardomacas** [comment]
There was a conflict and i resolved it. Checks may need to rerun but should be fine. Bound to have more conflicts as long as we dont merge it

**Review by ngayerie — APPROVED** [review]

**Review by rprice74 — APPROVED** [review]

**Review by ngayerie — APPROVED** [review]

**Review by kodster28 — APPROVED** [review]

**Pull request merged**
