### PR TITLE
Attempt to fix TableWrap usage on workers pricing page

### PR DESCRIPTION
**Pull request by a-robinson**
To fix broken DO pricing table.

This is mostly a shot in the dark, but the previous fix attempt (#2704) still doesn't appear to have helped in prod, so it shouldn't hurt to make the whitespace around these couple `TableWrap`s more similar to the others on the same page.

### CODE REVIEW

**Review by bretthoerner — APPROVED** [review]
My approval is also a shot in the dark. :)

**Comment by WalshyDev** [comment]
Oh, damn @a-robinson you _just_ beat me haha. Yes, this will fix it. The spacing means engine-docs doesn't see the line as empty. 

Will close my PR - https://github.com/cloudflare/cloudflare-docs/pull/2708

**Comment by a-robinson** [comment]
Ha only by one minute @WalshyDev. Thanks for finding and fixing the problem too!

**Review by greg-mckeon — APPROVED** [review]

**Comment by a-robinson** [comment]
Looks like this worked: https://developers.cloudflare.com/workers/platform/pricing#durable-objects

**Pull request merged**
