### PR TITLE
r2: add examples for downloading files using API tokens

### PR DESCRIPTION
**Pull request by elithrar**
This PR adds examples on how to authenticate against the R2 API using auth tokens in JavaScript (Node.js), Go, and Python 3.

cc @harshil1712

### CODE REVIEW

**Comment by harshil1712** [comment]
@elithrar, we already have examples for Pre-signed URL in our docs.

JS -> https://developers.cloudflare.com/r2/examples/aws/aws-sdk-js-v3/
Go -> https://developers.cloudflare.com/r2/examples/aws/aws-sdk-go/
Python -> https://developers.cloudflare.com/r2/examples/aws/boto3/

I thought you were asking about code examples on creating the tokens via the API.

**Comment by elithrar** [comment]
These aren't for pre-signed URLs. They are for direct token access. 

What parts have you believing otherwise?

**Comment by harshil1712** [comment]
Ah, my bad. The first part of the pre-signed URL examples are the same as the one in this PR. The only difference I could figure out was the hashed Secret Access Key. I didn't know this was a possibility.

**Review by dcpena — APPROVED** [review]

**Comment by elithrar** [comment]
@dcpena @harshil1712 - can one of you update this for the new docs engine? This didn't get merged before the migration.

**Comment by dcpena** [comment]
Closing in favor of https://github.com/cloudflare/cloudflare-docs/pull/16488 which recreates this PR post docs migration.

**Pull request closed without merging**
