### PR TITLE
Update code from service worker to module worker format

### PR DESCRIPTION
**Pull request by vicb**
### Summary

Update code from service worker to module worker format

### Documentation checklist

- [x] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.

Question:

I have added only the used parameters

```js
async fetch(request): Promise<Response>
```

The full signature is 

```js
async fetch(request, env, ctx): Promise<Response>
```

Specifying only the used parameters is valid syntax.
Are there guidelines to prefer one over the other syntax?

My plan is to convert most example to using the new syntax as the old syntax is deprecated. I'll send more PR after this one gets in.

### CODE REVIEW

**Review by irvinebroque — APPROVED** [review]

**Comment by vicb** [comment]
Let's use `async fetch(request, env, ctx): Promise<Response>`

**Comment by vicb** [comment]
As discuss we Brendan, I updated the PR to always use 

```js
async fetch(request, env, ctx): Promise<Response>
```

even if `env` and `ctx` are unused (because not supported in the legacy service worker)

**Comment by vicb** [comment]
@ToriLindsay @dcpena - can we get ✅ to merge this?

**Review by ToriLindsay — APPROVED** [review]

**Comment by ToriLindsay** [comment]
@vicb Approved. Thanks!

**Review by dcpena — APPROVED** [review]

**Comment by vicb** [comment]
Thanks for the review and merge!

**Pull request merged**
