### PR TITLE
fix code formatting

### PR DESCRIPTION
**Pull request by vicb**
### Summary

fix formatting

### Documentation checklist

- [x] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.

### CODE REVIEW

**Comment by vicb** [comment]
@cloudflare/workers-docs @cloudflare/pcx-technical-writing can this be merged?

**Comment by pedrosousa** [comment]
Hi @vicb 
Actually, we're now using `prettier` on file save and we're using tabs to indent code blocks (also done by `prettier`). I'll give it one last pass locally to update the file, which will fix the indentation as you intended.

**Review by pedrosousa — APPROVED** [review]

**Comment by vicb** [comment]
Hey @pedrosousa,

Thanks for your help.

I have a few questions for you:

> Actually, we're now using prettier on file save

Using prettier is great - there are a lot of inconsistencies in the docs.

Why don't we format all the docs with that instead of doing it only on file save?

It would require to update [the format script](https://github.com/cloudflare/cloudflare-docs/blob/0cc038b3bcfa9377e02296fe62c12242d030ceed/package.json#L14
) to include md and mdx files. 

We would also probably need to add a few [ignored folders](https://github.com/cloudflare/cloudflare-docs/blob/production/.prettierignore).

I don't see any blockers on doing that and we would have a consistent formatting.

If the whole docs are formatted some PR might get merge conflicts but it would be easy to format them to remove the conflicts. I can help with that if needed.

Let me know what you think, is this has been discussed already or if I need to create a feature request.

The second question is to understand how PRs are merged in this repo. This PR is now approved, when will it get merged?
I have [another PR](https://github.com/cloudflare/cloudflare-docs/pull/17506) that is waiting to be merged. No rush, I only want to understand the workflow here.

Thanks.

**Comment by pedrosousa** [comment]
The use of `prettier` is definitely not consistent. We're checking internally whether our config is the best one (`prettier` can be a bit finicky with MD/MDX + tabs) and how we would approach a more global update.

I'll merge the PR now that the checks have finished. 

Usually the assigned tech writer handles the review and the merge, but this may take a few days. Other internal folks with write access can also approve and merge PRs (usually when they're smaller or urgent).

**Comment by vicb** [comment]
Thanks @pedrosousa!

>  We're checking internally whether our config is the best one (prettier can be a bit finicky with MD/MDX + tabs) and how we would approach a more global update.

Let me know if there is anything I can help with here. Inconsistencies are bothering me so I would love to help unblock a global update.

**Pull request merged**
