### PR TITLE
[d1] fix location hint typo

### PR DESCRIPTION
**Pull request by eliblock**
Resolve a typo in the D1 docs: `whne` => `when`.

### CODE REVIEW

**Review by elithrar — APPROVED** [review]
Thanks!

**Comment by eliblock** [comment]
@elithrar - thank you for the review! What is the process from here: will you or another maintainer merge (it looks like repo write access is required)?

**Comment by elithrar** [comment]
@eliblock I had to wait for CI to run 😃

**Comment by eliblock** [comment]
@elithrar makes sense 🙃 - thank you!

FYI: I re-read the [contribution guidelines](https://github.com/cloudflare/cloudflare-docs/blob/3cc3908633bfc28d0d1e916dd01095d4cee77846/CONTRIBUTING.md) before asking, but after reading the last paragraph wasn’t sure if merging was something for me or for your team to handle.

**Pull request merged**
