### PR TITLE
Update code from service worker to module worker format

### PR DESCRIPTION
**Pull request by vicb**
### Summary

Remove the last workers code snippets using the Service Worker syntax - work started in #17905

@irvinebroque We still have a few snippets using both syntaxes (see the tabs on top):

image

I'm in favor or dropping the Service Worker syntax from there too:
- to be consistent in only using the Module syntax
- to not have to maintain that doc/code
- to stop promoting that deprecated format

Thoughts?

/cc @ToriLindsay

### CODE REVIEW

**Review by irvinebroque — APPROVED** [review]

**Comment by vicb** [comment]
@ToriLindsay could you please help get this PR in?

semgrep errors are false positive and might be fixable in the UI but I don't have access.

Thanks

**Review by ToriLindsay — APPROVED** [review]

**Comment by ToriLindsay** [comment]
@dcpena @angelampcosta @RebeccaTamachiro Can you approve or confirm that this can be merged since it affects your docs too?

**Comment by ToriLindsay** [comment]
> @ToriLindsay could you please help get this PR in?
> 
> semgrep errors are false positive and might be fixable in the UI but I don't have access.
> 
> Thanks

Update: I'm working on getting access and also asking someone on my team for help

Update: I can merge as soon as the other PCX writers whose docs are affected confirm. I've also reached out to them via chat.

**Review by dcpena — APPROVED** [review]

**Review by angelampcosta — APPROVED** [review]

**Comment by vicb** [comment]
Thanks all for the reviews!

**Pull request merged**
