### PR TITLE
Fix hyperdrive create invocations

### PR DESCRIPTION
**Pull request by a-robinson**
They shouldn't include "database" anymore, and they need a closing quotation mark.

### CODE REVIEW

**Comment by a-robinson** [comment]
@elithrar feel free to close this, but it seemed easier than making you go and update the other file as well on #10980

**Comment by a-robinson** [comment]
@elithrar @Maddy-Cloudflare this fixed a couple instances more than #10980 did, so we still ought to get this in.

**Review by Maddy-Cloudflare — APPROVED** [review]

**Review by elithrar — APPROVED** [review]

**Comment by a-robinson** [comment]
Uhhh so the builds are failing for issues that are preexisting and have nothing to do with my change. Am I expected to fix them myself in order to merge this? Or what's the path forward to getting this in?

**Comment by a-robinson** [comment]
Pushed up a fix for the spell check complaint, but I'm not actually sure what's going wrong with the other failing check. It looks like a real problem but has to do with how the markdown is being rendered into HTML?

**Comment by a-robinson** [comment]
Although the "real problem" is there on the production branch too, not just this one. So IDK.

**Comment by a-robinson** [comment]
I take it all back, apparently the build is happy now? I don't know what's going on, but I guess we're all good.

**Pull request merged**
