### PR TITLE
[Fix]:Fix active tab issue in light mode

### PR DESCRIPTION
**Pull request by Ekwuno**
**Before**
Typescript selected
Screenshot 2022-08-05 at 12 12 06

Javascript selected
Screenshot 2022-08-05 at 12 12 17

**After**

Javascript selected
Screenshot 2022-08-04 at 23 55 18

Typescript selected 
Screenshot 2022-08-04 at 23 55 25

### CODE REVIEW

**Review by lauragift21 — COMMENTED** [review]
I see you removed a bunch of code, can you share a screenshot of change before, I'm not sure which of these changes is related to the active tab issue.

**Comment by Ekwuno** [comment]
@lauragift21 I added back the short code so you can see what it looks like now here https://fix-active-tab-issue.cloudflare-docs-7ou.pages.dev/pages/platform/functions/

**Review by lauragift21 — APPROVED** [review]
lgtm!

**Comment by Ekwuno** [comment]
Updated the description as well

**Pull request merged**
