### PR TITLE
[Cloudflare Docs] Add URLs for testing

### PR DESCRIPTION
**Pull request by Robert941**

### CODE REVIEW

**Comment by Robert941** [comment]
@abracchi-tw This is related to my other pull request.

**Comment by Robert941** [comment]
Hello, before merging this, do I have to fix the conflicts or are you able to?

**Comment by kodster28** [comment]
@marciocloudflare, is this info accurate for testing? If so, seems like an easy add to https://developers.cloudflare.com/1.1.1.1/setup/check-1.1.1.1/

**Comment by marciocloudflare** [comment]
Closing as it's out of sync with the docs, but feel free to reopen. I'm checking with the team if it makes sense do document. Thanks

**Pull request closed without merging**
