### PR TITLE
Update bulk analytics page: move aside below title

### PR DESCRIPTION
**Pull request by renandincer**
cc @zaidf

### CODE REVIEW

**Comment by renandincer** [comment]
Fixes issue introduced in https://github.com/cloudflare/cloudflare-docs/pull/1594

**Review by kodster28 — APPROVED** [review]

**Comment by kodster28** [comment]
Approved from a content perspective. I'll leave it up to you to merge in.

**Comment by marciocloudflare** [comment]
I noticed this problem when working on Stream Live and solved it in that PR. So I think we can go ahead and close this one.

**Comment by kodster28** [comment]
Based on @marciocloudflare's feedback, going to go ahead and close this PR.

**Pull request closed without merging**
