### PR TITLE
Fix broken url in docs

### PR DESCRIPTION
**Pull request by saintmalik**
## Summary

Easy navigation and easy reading for others

### CODE REVIEW

**Comment by agneevX** [comment]
Why not create 1 PR instead of 11?

**Comment by saintmalik** [comment]
Sorry please, the detection of the dead URLs are manually, that is why I am
editing it page by page.🙇

**Review by abracchi-tw — APPROVED** [review]

**Comment by agneevX** [comment]
@saintmalik just commit to the same branch and create one PR from that branch :)

**Comment by saintmalik** [comment]
Okay cool, I will do that in next pull request, Thanks so much😌

**Pull request merged**
