### PR TITLE
D1: Update community-projects.md

### PR DESCRIPTION
**Pull request by elithrar**
Remove t4 stack.

### CODE REVIEW

**Review by Maddy-Cloudflare — APPROVED** [review]

**Comment by albbus-stack** [comment]
Hey, could you elaborate on why you removed t4 stack? All of its community is using d1 and the template is meant to be used with d1 out of the box, I don't get why it shouldn't be a community project but maybe you can enlighten me. All things said keep up the amazing work 🤟

**Comment by j3sch** [comment]
Hi, I've been using T4 Stack for a while now and am very happy with it. I was looking for a boilerplate for cross platform apps that uses Cloudflare Workers because of the performance. I’ve noticed that the T4 Stack has recently been removed from the list of community projects in the documentation and wondered why. May I know the reasons behind this? Thanks

**Comment by wynnej1983** [comment]
What is the logic behind removing t4stack? I'm using cloudlfare and d1 for the first time thanks to t4stack.com.
maybe theo from t3 stack was onto you guys complaining lol?
put it back in please, its excellent!

**Comment by guioum** [comment]
I am not aware of fullstack typescript stacks that are leveraging the possibilities of Cloudflare more than t4. They even work on authentication over d1.

**Pull request merged**
