### PR TITLE
Fix Header Links

### LINKED ISSUE #12708: Broken Header Links Found
Specific header links in the [Workflow Run](https://github.com/cloudflare/cloudflare-docs/actions/runs/7682100797).

Generally, we expect you to address at least 10-15 links before closing this out.

### PR DESCRIPTION
**Pull request by helloimalastair**
Closes #12708.
Preview [available here](https://fix-header-links.cfdocs-alastair.pages.dev/).

Also, how do y'all disable the `target is a directory, no index` error from popping up on the Workflow run? I'm running the same command locally, and I get almost 200 extra errors for that...

### CODE REVIEW

**Comment by kodster28** [comment]
Thanks for helping fix these headers, @helloimalastair!

Which workflow run are you referring to on the error `target is a directory, no index` + what type of machine are you running?

**Comment by helloimalastair** [comment]
@kodster28 I'm running the [Anchor Link Audit](https://github.com/cloudflare/cloudflare-docs/blob/production/.github/workflows/anchor-link-audit.yml) workflow, or as closely as I can locally. I've built the docs locally(as visible in the Pages project), then run `htmltest -c ./bin/.htmltest.yml` on it. `htmltest`, in this case, is installed via Homebrew, but it is the same version as the one installed in Actions(`v0.17.0`). I'm on an M1 Mac, if that has any influence. As for the logs, here's what is outputted(on my fixed branch): [nopaste link](https://nopaste.ml/#XQAAAQB6PQAAAAAAAAA0HQneXNfztcPESybGwzXZXy+Ulu4p8HBeguh1xqxIIs9oKBV4cjRFXlnmmgsWAxVg4dUeD19l3Im/ArkvAZ9T0e1p5uRKkqmCXPBHwrDMnMi8IrISnmmF68n+h3erzQ0V36NP8horUyxs2+42BMAxXNsXDn6IzUbXE9oojvawX4PGSoer6v7KZwbOAiPWCVC39KRIMIi2SHEvlFb5PSeov/MDXe9UvvKu7xKLbMK2mmc4JNmfswxHvyjiy6T1XlCyvenStzj04q8cZQSNVqNx15lP49djqKudafbJAmitnLfZin8AKNm/NSCWLXA80a12sySs1GCBbcLmwsDsjKEvNQXd2Bls3KkVFmbT+7P7bKXhD3R2mA4/ArAn7YSsCwG02RzSunTzbeUODIn2U+y1ViiO5dzyapiQxgGt79KROuSChXJZjl3Zqhh+MAY7e/3PGngbFuN9HO76dbmwWz8FgdL9PmQ6V15rToUeeA++b3UQHWNPnp9oi982RL4NU9wx7TtueCsp4XVB5dCN4Fx1Z7nviQAEWTpytTaB2nSr0CvUCvrORk8HCTeOL3cVeuBhRirAZj0zqjWxaciAAYAEiq46dIHe75QIh0JhW3yniLKBfscqV+r+cpx4k/7nKtBt69VVQrOWguTSY6z5+29ZNe+/vaGhwq3KwrQgu2xqIGIOn0+9/7jA/oLkot65Ycw0rIb2QqHjg5IZbDN2c0kEwkn6Dl+X/OkIFvhpuTDletUtDUnrtxtQ2uDU4AV5QgyM+33t0KhDFJ7LWQa/uynuuAKXg0lIXmxeZwX8TRxMOf3Ltfewvp+2ZP4+dOfVxVdHsKYlddG/KVmDTF1s69j14qfNATcOsQC05Kjiz857FQo5NPLDnop6OC1CGYva6xX5boDbkfjtzbGgfRocREtCqtiz22goAV1pt0XJkEHOKr34YAeiGVPZX6tAS5rLaYFHSJT9wZnQh0X/mNZa6JtDOj+NQCPP484rAqAniGhxDKqvbLvwh+IG5OPpwy5U9PZAglRQm+a8mNec62Vtd5Y9kzjZvFJ/N/0anZE5lGHp5H38A9cg3TO5cl1JHcFI/IkU+CPG2y8uKCqdBKJz/2fE4t6p9sdUgYPG6G6JHZc5Wg+U3DMhocWGY/TeU1DUKNv2JDNZX9P8gG6TvXLFrI8UpF0i62oM6xv+ULX+qJyN)

**Comment by kodster28** [comment]
Ah... for the most part, I think our team only uses this check when run through GitHub actions itself (as opposed to locally). For whatever reason, there's none of that noise in the [remote output](https://github.com/cloudflare/cloudflare-docs/actions/runs/7682100797/job/20936036279#step:9:7), as I'm sure you've seen.

Is it common for you / others to run the anchor link auditing on a local branch?

**Comment by kodster28** [comment]
Think this should be solved once we merge in #12733.

Here's my local output after adjusting the config, deleting `/public`, rebuilding, and then re-running htmltest.

Screenshot 2024-01-29 at 4 33 41 PM

**Comment by helloimalastair** [comment]
Other than that, this PR should be ready, unless there is something I missed?

**Comment by kodster28** [comment]
> Other than that, this PR should be ready, unless there is something I missed?

Correct! I'll pull down locally and resolve those merge conflicts first though.

**Review by kodster28 — APPROVED** [review]

**Comment by kodster28** [comment]
TY for helping with this, @helloimalastair!

**Comment by helloimalastair** [comment]
> Is it common for you / others to run the anchor link auditing on a local branch?

Oh hey, somehow didn't see this reply before now. I can't speak for others, but I like running it just as a way to check that I got everything, faster than manually matching each page from the Actions log.

**Pull request merged**
