### PR TITLE
Update link color 

### PR DESCRIPTION
**Pull request by Ekwuno**

### CODE REVIEW

**Comment by pedrosousa** [comment]
In the preview I can still see different link colors:

image

image

image

Not sure if this PR was expected to fix all these situations or not.

The links to the above pages are the following:
https://b99aac1d.cloudflare-docs-7ou.pages.dev/waf/custom-rules/custom-firewall/skip/options/
https://b99aac1d.cloudflare-docs-7ou.pages.dev/waf/custom-rules/rate-limiting/
https://b99aac1d.cloudflare-docs-7ou.pages.dev/ruleset-engine/rules-language/fields/

**Comment by kodster28** [comment]
Relates to #3928

**Comment by kodster28** [comment]
Any progress on this? Even if it doesn't fix all the issues, if it solves more of them, that's probably better from a usability standpoint.

**Comment by Ekwuno** [comment]
@kodster28 thanks for highlighting this again. I will look it it.

**Pull request closed without merging**
