### PR TITLE
[Logs] Update Log fields

### PR DESCRIPTION
**Pull request by soheiokamoto**
This updates Log fields for:
 - `gateway_http`
 - `gateway_network`
 - `zero_trust_network_sessions`

It is synced from internal `logshare-api` repo's fields templates.

### CODE REVIEW

**Comment by soheiokamoto** [comment]
Losing changes from https://github.com/cloudflare/cloudflare-docs/pull/8138, as they were not updated in the internal source (`data/logshare-api`).

**Review by bharatnc — APPROVED** [review]

**Comment by soheiokamoto** [comment]
> Losing changes from #8138, as they were not updated in the internal source (`data/logshare-api`).

Fixed in the internal source.

**Review by angelampcosta — APPROVED** [review]

**Comment by angelampcosta** [comment]
@soheiokamoto should we merge this PR?

**Comment by soheiokamoto** [comment]
> @soheiokamoto should we merge this PR?

Yes. Merging.

**Pull request merged**
