### PR TITLE
add links to NR I/O quickstart page from the NR doc

### PR DESCRIPTION
**Pull request by jcountsNR**
Hi Cloudflare team, I noticed most of the links and web search traffic for NR/Cloudflare logpush integration leads to [this page](https://developers.cloudflare.com/logs/get-started/enable-destinations/new-relic/). This gives great info on setting up the logpush, but doesn't mention the next step of actually installing the quickstart and seeing the visualizations. I added an extra section here based on the analytics integrations page I found, and linked to the quickstart in NR. Let me know if this is reasonable or needs any changes, thanks!

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202663307643661

### CODE REVIEW

**Comment by angelampcosta** [comment]
Hi @jcountsNR Thank you so much for your feedback. Actually the analytics integrations live on another section: https://developers.cloudflare.com/fundamentals/data-products/analytics-integrations/new-relic/

**Comment by jcountsNR** [comment]
@angelampcosta thanks! I noticed this when I forked the Repo, but I had not seen it prior. Is it possible that this page does not get as much traffic as the logpush page? Maybe instead of duplicating it we could just add a link to this page for the next steps.

**Comment by angelampcosta** [comment]
@jcountsNR The logpush page does get a bit more page views, but overall they're relatively comparable. Thank you for your suggestion, I think it makes sense to add a link to the integration page. I'll follow up on that on a ticket.

**Comment by jcountsNR** [comment]
@angelampcosta , sure, thanks!

**Pull request closed without merging**
