### PR TITLE
Added new know issue

### PR DESCRIPTION
**Pull request by Triloworld**
After auditing it was found. More details in this ticket. 
https://support.cloudflare.com/hc/en-us/requests/2234939

(Can someone check if no spelling mistake was introduced? thx)

### CODE REVIEW

**Comment by Ekwuno** [comment]
Hello @Triloworld do you mind providing more context to this? The ticket, you linked, points to a 404.

**Comment by WalshyDev** [comment]
This was about changing the minimum TLS version (https://dash.cloudflare.com?to=/:account/:zone/ssl-tls/edge-certificates -> "Minimum TLS Version") not being respected with Pages.

This is no longer an issue and can be closed out, to confirm this you can test on my Pages site:
`curl --tls-max 1.1 https://walshy.dev` - Fails
`curl --tls-max 1.2 https://walshy.dev` - Works

Edit: I should add that all sites added **before** the fix got grandfathered into it. The site would need to be re-added for the settings to apply.

**Comment by Triloworld** [comment]
I re-apply setting and this problem still occur. 

`curl --tls-max 1.1 http://5gmadetogether.com` - Works
`curl --tls-max 1.2 http://5gmadetogether.com` - Works

https://www.ssllabs.com/ssltest/analyze.html?d=5gmadetogether.com&s=2606%3a4700%3a3033%3a0%3a0%3a0%3a6815%3a68a&hideResults=on&latest

Set as "Minimum TLS Version" to TLS 1.2

**Comment by WalshyDev** [comment]
Yeah, you need to delete the Pages project re-add it. I'm assuming you just re-set the value.

**Comment by Ekwuno** [comment]
Yea, I was confused because  ` curl --tls-max 1.1 https://www.obinnaspeaks.dev/ - fails `. I will go ahead and close this now. @Triloworld please let me know if you have any other issues after adding your site again.

**Comment by Triloworld** [comment]
Yes. It working right now ! Thx! It was yesterday some error in custom domain registration. 
I must re-add page project with custom domain. Getting full score and no accepted connection for TLS 1.0 or 1.1

**Pull request closed without merging**
