### PR TITLE
Fix `kv_namespaces` position in wrangler config documentation

### PR DESCRIPTION
**Pull request by askolesov**
`kv_namespaces` is a top level config property (not a property of `[vars]`). Spent some time figuring this out.

### CODE REVIEW

**Comment by lukeed** [comment]
Had it been `[[kv_namespaces]]` format, it wouldn’t have fallen under the vars namespace. TOML is weird

**Comment by askolesov** [comment]
Agreed, `[[kv_namespaces]]` is even better option

**Comment by deadlypants1973** [comment]
> Agreed, `[[kv_namespaces]]` is even better option

Hi @askolesov , Can you rewrite this PR with this option instead? :)

**Comment by deadlypants1973** [comment]
fixed in #5051

**Pull request closed without merging**
