### PR TITLE
[Teams] cert pinning + regex docs

### PR DESCRIPTION
**Pull request by abracchi-tw**
we're not going to add the cert pinning hostnames table for now.
Just adding regex docs

### CODE REVIEW

**Review by ptzimmerman — CHANGES_REQUESTED** [review]
Let's wait on this for now since this list of hostnames is going to change

We should also keep a few example rules of how to bypass

**Comment by abracchi-tw** [comment]
> Let's wait on this for now since this list of hostnames is going to change

@ptzimmerman could we merge this and then update the list when it changes?

**Comment by abracchi-tw** [comment]
@ptzimmerman added the table with bypass rules back

**Review by TownLake — APPROVED** [review]

**Review by ptzimmerman — CHANGES_REQUESTED** [review]
@abracchi-tw we made updates to the hostname list:
https://bitbucket.cfdata.org/projects/DOPE/repos/applications/browse/definitions/cert-pinning.yaml

**Review by ptzimmerman — APPROVED** [review]

**Pull request merged**
