### PR TITLE
Add build documentation for Jigsaw

### PR DESCRIPTION
**Pull request by bakerkretzmar**
Adds an entry in the list of common tools for the [Jigsaw](https://github.com/tighten/jigsaw) static site generator.

### CODE REVIEW

**Comment by kristianfreeman** [comment]
@bakerkretzmar do you have a test repo I can verify this deploy with? thanks!

**Comment by bakerkretzmar** [comment]
Sure, my personal website is built with Jigsaw, the repo is here: https://github.com/bakerkretzmar/bakerkretzmar.ca. The Jigsaw docs also use Jigsaw: https://github.com/tighten/jigsaw-site.

I just hooked up my own site to Cloudflare Pages and deployed it with no changes to https://bakerkretzmar.pages.dev. Build log is here, looks like it's a private link but maybe you can look up the project and see it: https://dash.cloudflare.com/d634935c5870a4b3a24e86daeb3776e5/pages/view/bakerkretzmar/5e58bbbb-5105-4c8f-867a-c506579e90b6.

**Comment by kristianfreeman** [comment]
thanks @bakerkretzmar! testing now by deploying the jigsaw docs 🧩

**Comment by kristianfreeman** [comment]
hey @bakerkretzmar, i'm not super familiar with PHP, so i may need some help! for the jigsaw docs, I was able to run `npm run production` to build and deploy, but on your personal site, the build doesn't seem to work with the `vendor/bin/jigsaw build` command in this table. i also see that pages tries to install dependencies, but it looks like there's an error. is there any sort of pre-build steps that we need to document as well? thanks!

**Comment by bakerkretzmar** [comment]
@signalnerve great point, sorry about that!

My site has custom source/destination directories. It looks like the build command is waiting for a prompt to confirm overwriting the custom destination even if it doesn't exist yet, so I'll work on fixing that in Jigsaw itself. The `public` directory, which it's asking to overwrite for my personal site, doesn't exist in the repo, so once this is fixed my site should work with `vendor/bin/jigsaw build` too.

For standard Jigsaw sites, `vendor/bin/jigsaw build` will work. The default destination is `build_{environment}`, (e.g. `build_local` or `build_production`), which will always be overwritten without prompting.

I don't think there were issues installing dependencies, I went back over the build logs and all the npm and Composer deps were installed successfully.

I wasn't sure whether it was better to put `vendor/bin/jigsaw build` or `npm run production`, most Jigsaw sites in the wild have CSS and many have JavaScript, so they almost all actually build with `npm run production`, but looking at the other site builders in the list I kept `vendor/bin/jigsaw build` because that is Jigsaw's actual build command.

**Comment by kristianfreeman** [comment]
> @signalnerve great point, sorry about that!
> 
> My site has custom source/destination directories. It looks like the build command is waiting for a prompt to confirm overwriting the custom destination even if it doesn't exist yet, so I'll work on fixing that in Jigsaw itself. The `public` directory, which it's asking to overwrite for my personal site, doesn't exist in the repo, so once this is fixed my site should work with `vendor/bin/jigsaw build` too.
> 
> I wasn't sure whether it was better to put `vendor/bin/jigsaw build` or `npm run production`, most Jigsaw sites in the wild have CSS and many have JavaScript, so they almost all actually build with `npm run production`, but looking at the other site builders in the list I kept `vendor/bin/jigsaw build` because that is Jigsaw's actual build command.

Really sorry for the delay here. Happy to help get this over the finish line if we can get a working sample repo! As for _how_ to configure it - generally, I think the vendor command is preferable (so users don't need to define custom NPM scripts). What do you think about that?

**Comment by bakerkretzmar** [comment]
@signalnerve no worries!

Here's a working sample I just deployed, it's Jigsaw's basic site scaffold with no changes at all: https://github.com/bakerkretzmar/jigsaw-pages-demo.

And here's the [live site](https://3f9987f4.jigsaw-pages-demo.pages.dev/) and [deployment log](https://dash.cloudflare.com/d634935c5870a4b3a24e86daeb3776e5/pages/view/jigsaw-pages-demo/3f9987f4-a983-448d-ac50-eafd23f23b92). These are the settings I used:

image

**Review by kristianfreeman — APPROVED** [review]

**Comment by bakerkretzmar** [comment]
Thanks!

**Comment by georgeboot** [comment]
@signalnerve  sorry to spam here, but where can I request support for PHP 8.0 on pages? I have been using Pages with JigSaw for a while but want to build using PHP 8.0. However, that version is not available. Posted on the community but no reply for months.

**Pull request merged**
