### PR TITLE
Fix compat matrix

### PR DESCRIPTION
**Pull request by WalshyDev**
### Summary
* Pages does support DOs deployed by a Worker
* Pages does _not_ support rate limiting

### Documentation checklist

- [x] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [x] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [x] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

### CODE REVIEW

**Review by dcpena — APPROVED** [review]

**Comment by GregBrimble** [comment]
**Totally** not sold on the idea, but _maybe_ worth breaking it into two rows "can own a Durable Object" and "can bind to a Durable Object" or something like that? à la Queue consumers and Queue producers? Maybe just "Durable Objects" and "Durable Objects bindings"? @tanushree-sharma , any opinion?

**Comment by tanushree-sharma** [comment]
Agree ^. Have heard pain points with Pages limitation of only being able to bind to a DO. Breaking it up to make it clear is a good idea.

**Comment by dcpena** [comment]
Hi there @WalshyDev! Is this ready to merge or still a WIP? If it's still being worked on, would you mind putting this in draft mode so the PCX team knows if it needs merged or not?

**Comment by dcpena** [comment]
I'm fairly certain the updates in https://github.com/cloudflare/cloudflare-docs/pull/17303 cover the updates in this PR. Closing, but @WalshyDev please feel free to reopen if I'm incorrect!

**Pull request closed without merging**
