### PR TITLE
add example apps for R2 and D1

### PR DESCRIPTION
**Pull request by harshil1712**

### CODE REVIEW

**Review by kodster28 — APPROVED** [review]

**Comment by vy-ton** [comment]
@kodster28 @harshil1712 Can we walk through whats the intended difference between examples, demos, and tutorials?

**Comment by kodster28** [comment]
> @kodster28 @harshil1712 Can we walk through whats the intended difference between examples, demos, and tutorials?

Sure! 

A bit of an in-progress definition, but the way I conceptualize it is:

- **Tutorial**: A narrative journey taking someone from a clear starting to ending point. Could eventually end up being paired with an app or include an example, but definitely something extra.
- **Example**: Something I -- as a developer -- can copy/paste and it just works. Might require a touch more setup... but ideally works out of the box.
- **Demo**: A working app that has a dedicated GitHub repo someone can clone. More involved / elaborate than an example. May be included as part of a tutorial.

A helpful way for me in thinking through this `what are the maintenance tasks` associated with this piece of content. (tutorial - walk through end-to-end / example - test copy/paste / app - clone and deploy)

Could be overcomplicating this and maybe `example` fits for app / examples too... definitely open to chatting more about this.

**Comment by elithrar** [comment]
Agree with Kody on the differences here. In practice w/ Hyperdrive:

* Hyperdrive examples - simple copy-paste snippets: https://developers.cloudflare.com/hyperdrive/examples/
* Tutorial - "how to build SOMETHING" - https://developers.cloudflare.com/hyperdrive/tutorials/serverless-timeseries-api-with-timescale/
* Demo - an interactive app/site we host: https://hyperdrive-demo.pages.dev/

**Comment by vy-ton** [comment]
+1 I like the split/differentiation, could be nice to have top-level section that walks readers thru the categories as well? I would definitely be prone to opening all 3 sections

**Comment by kodster28** [comment]
> +1 I like the split/differentiation, could be nice to have top-level section that walks readers thru the categories as well? I would definitely be prone to opening all 3 sections

A top-level section in addition to these three sections... or one that contains Examples / Tutorials / Demos? I'd be a bit concerned about either of those approaches b/c the former might crowd the top-level nav + the latter might bury valuable resources.

Definitely open to thinking / chatting about that more.... but as an interim solution, thoughts on me using our `glossary-tooltip` component to provide more context about the terms at the top of the page?

Screenshot 2024-07-15 at 8 49 15 AM

You can see a live example of tooltips in [our style guide](https://developers.cloudflare.com/style-guide/documentation-content-strategy/component-attributes/glossary-entry/#glossary-tooltip)

**Comment by vy-ton** [comment]
I lean towards `or one that contains Examples / Tutorials / Demos` but tool tip as interim sgtm.

**Review by vy-ton — APPROVED** [review]

**Review by maxvp — APPROVED** [review]

**Pull request merged**
