### PR TITLE
[Docs site] Separated api docs into separate tab

### PR DESCRIPTION
**Pull request by kodster28**
Replaces #7976

### CODE REVIEW

**Review by KimJ15 — APPROVED** [review]

**Review by WalshyDev — APPROVED** [review]
Nice solution, thanks Kody!

**Comment by kodster28** [comment]
A. Thanks @WalshyDev!
B. Doubt it'll take too long, but we'll need to hold this a bit until @codewithkristian can help us get the link updated on the API docs frontend.

**Comment by Cherry** [comment]
This is an awesome solution - way better than my attempt! Thanks Kody 🧡

**Comment by kodster28** [comment]
Thanks for the suggestion, @Cherry!

**Pull request merged**
