### PR TITLE
chore(redirects): updates redirects for settings

### PR DESCRIPTION
**Pull request by jacobbednarz**
301s a bunch of old URLs to the new operation ID path in the developer documentation.

In essence:

- `zone-settings-change-.+` => `zone-settings-edit-single-setting`
- `zone-settings-get-.+` => `zone-settings-get-single-setting`

### CODE REVIEW

**Comment by jacobbednarz** [comment]
tried to test the redirects here however, it looks like they aren't deployed to the feature branch preview.

**Comment by jacobbednarz** [comment]
@GregBrimble actually - this may not work here depending on the call order of the two separate repositories. are you able to confirm where these redirects _should_ live if it won't work as is?

**Comment by GregBrimble** [comment]
`_redirects` only take effect at the lowest, static asset serving, level. If `/api` is being served by Pages Functions or another Worker route, that'll execute before `_redirects` even have an opportunity to execute. You'll need to handle the redirects in the application above this.

**Comment by jacobbednarz** [comment]
assumed as much. i _suspect_ it is a different route so we'll need to do this further up.

**Pull request closed without merging**
