### PR TITLE
Update identity-selectors.md

### PR DESCRIPTION
**Pull request by kennyj42**
the current version was really incorrect. You can't reference access groups in the Gateway policy builder.

### CODE REVIEW

**Comment by ranbel** [comment]
The point we were trying to make is that you have to go into Access to figure out which Gateway selector to use for a particular IdP: group names, group ID, or SAML. It's not always going to be SAML.

We can improve the wording so people don't try to use Access groups in Gateway.

**Comment by kennyj42** [comment]
If you're using SAML, the only option you have is SAML Attributes. The Group Name/ID fields will not work for SAML idps since we don't know what the group value is called in a custom SAML integration.

**Comment by ranbel** [comment]
How about for OIDC IdPs?

**Comment by kennyj42** [comment]
They're not supported in Gateway policies until we add OIDC Claims as a selector.

**Comment by ranbel** [comment]
So in summary:
- User Group IDs is only available with AzureAD.
- User Group Names is only available with GitHub, Google, or Okta (OIDC). No other OIDC providers are supported.
- SAML Attributes is available for all SAML providers.
- User Group Emails --> which IdPs are supported?

**Comment by kennyj42** [comment]
AzureAD is also supported via Group Name if they enable SCIM.

I believe User Group Email should be supported for all IdPs.

**Review by ranbel — APPROVED** [review]

**Pull request merged**
