### PR TITLE
[Durable Objects] add waitUntil()

### PR DESCRIPTION
**Pull request by haneefmubarak**
@greg-mckeon @koeninger

### CODE REVIEW

**Comment by koeninger** [comment]
do we want to link to external docs, or to our internal nearest equivalent, e.g. https://developers.cloudflare.com/workers/learning/fetch-event-lifecycle#waituntil

**Comment by haneefmubarak** [comment]
In [Debugging Workers](https://developers.cloudflare.com/workers/learning/debugging-workers#setup-a-logging-service:~:text=you%20can%20pass%20the%20request%20promise) we link to the same source, so I think perhaps we could consolidate the 3 references for `waitUntil()` (`ScheduledEvent`, `FetchEvent`, and Durable Objects - this one) as links to a single short page about `waitUntil()` within the context of CF Workers, with a link referring to the web standard in question.

@koeninger  does that seem reasonable? I think it'd also help solidify that the APIs across different types of Workers aim to be relatively consistent in behavior unless noted otherwise.

**Comment by koeninger** [comment]
Ah, if we're already linking to the same source elsewhere it's probably
fine as is.

**Comment by haneefmubarak** [comment]
Re-ran, all checks passed. Seeing as no behavioral files changed, I think that was a transient error (network or something).

**Comment by koeninger** [comment]
Cool, lgtm but I think @greg-mckeon has approval rights on this repo, I don't currently

**Review by a-robinson — APPROVED** [review]
LGTM as well, but I also don't have merge privileges here AFAIK.

**Comment by haneefmubarak** [comment]
So funny thing that. You apparently have to do the review as `workers-docs` and then after that you or I can merge (I know this because I merged the last change to this file IIRC).

A "fun" little GH quirk if you will.

**Comment by haneefmubarak** [comment]
ah you're not a member of workers-docs, nvm

**Review by greg-mckeon — APPROVED** [review]

**Pull request merged**
