### PR TITLE
pages: add private-registry how-to

### LINKED ISSUE #942: Add instructions for using private npm registries with Pages
@signalnerve 

1. Create and check in a `.npmrc` file with your registry ([details](https://docs.npmjs.com/cli/v7/configuring-npm/npmrc))
2. If using an environment variable (which are automatically substituted in `.npmrc` files), set that variable in your deployment settings (or wherever the tab is for setting environment variables)

e.g.

.npmrc:
```
@myscope:registry=https://npm.myprivateregistry.com/
//npm.myprivateregistry.com/:_authToken=${MY_AUTH_TOKEN}
```

environment variable config:
| Key           | Value        |
|---------------|--------------|
| MY_AUTH_TOKEN | XXX-XXX-XX-X |

### PR DESCRIPTION
**Pull request by lukeed**
Couldn't really decide on a URL and H1 title 🤷 But I did verify that all this works with a real Pages site using private registries.

Closes #942

### CODE REVIEW

**Review by kristianfreeman — APPROVED** [review]

**Comment by miguelcobain** [comment]
@lukeed how can the build command `mv .npmrc.pages .npmrc && npm run build` work, if the build command runs **after** `npm install` itself?

By the time the `mv .npmrc.pages .npmrc` runs, the build already tried to npm install before and fails because there's no `.npmrc`.

**Comment by lukeed** [comment]
@miguelcobain Thanks, last night I noticed I had a dangling `preinstall` script locally 🙃 Sending in a follow-up PR

**Comment by miguelcobain** [comment]
@lukeed @signalnerve I think for the time being we should remove this how to, right?
It's leading people to a dead end...

**Comment by lukeed** [comment]
@miguelcobain There is a follow up to this w/ the fixes #1260

**Pull request merged**
